name = "glaze_up"
version = "0.1.0"

[dependencies]
gleam_stdlib = ">= 0.55.0 and < 1.0.0"
tom = ">= 1.1.1 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.3.0 and < 2.0.0"
